# Generated by Django 6.0.3 on 2026-04-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_address_alter_book_rating_author_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Address',
            new_name='address',
        ),
    ]
